//8 adet sefer için hazırladığım başlangıç temel verileri
export const allTravelData = [
  {
    id: 1,
    departCity: "İstanbul",
    arrivalCity: "İzmir",
    date: "2023-08-31",
    availableSeats: 14,
    price: 468,
  },
  {
    id: 2,
    departCity: "Ankara",
    arrivalCity: "Antalya",
    date: "2023-08-31",
    availableSeats: 16,
    price: 348,
  },
  {
    id: 3,
    departCity: "İstanbul",
    arrivalCity: "Antalya",
    date: "2023-08-31",
    availableSeats: 7,
    price: 398,
  },
  {
    id: 4,
    departCity: "Ankara",
    arrivalCity: "İzmir",
    date: "2023-08-31",
    availableSeats: 13,
    price: 412,
  },
  {
    id: 5,
    departCity: "İstanbul",
    arrivalCity: "İzmir",
    date: "2023-09-01",
    availableSeats: 14,
    price: 435,
  },
  {
    id: 6,
    departCity: "Ankara",
    arrivalCity: "Antalya",
    date: "2023-09-01",
    availableSeats: 16,
    price: 387,
  },
  {
    id: 7,
    departCity: "İstanbul",
    arrivalCity: "Antalya",
    date: "2023-09-01",
    availableSeats: 7,
    price: 477,
  },
  {
    id: 8,
    departCity: "Ankara",
    arrivalCity: "İzmir",
    date: "2023-09-01",
    availableSeats: 13,
    price: 365,
  },
];
