export interface Seat {
  row: number;
  col: number;
  isOccupied: boolean;
  passengerGender: string;
}

export interface BusSeatData {
  [x: string]: any;
  [key: number]: Seat[];
}

export const busSeatData: BusSeatData = {
  1: [
    { row: 0, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 0, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 0, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 0, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 1, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 2, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 3, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 3, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 3, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 4, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 3, isOccupied: false, passengerGender: "null" },
  ],

  2: [
    { row: 0, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 0, col: 1, isOccupied: true, passengerGender: "male" },
    { row: 0, col: 2, isOccupied: true, passengerGender: "male" },
    { row: 0, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 1, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 2, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 3, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 3, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 4, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 3, isOccupied: true, passengerGender: "male" },
  ],
  3: [
    { row: 0, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 0, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 0, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 0, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 1, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 2, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 3, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 3, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 3, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 4, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 3, isOccupied: true, passengerGender: "male" },
  ],
  4: [
    { row: 0, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 0, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 0, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 0, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 1, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 2, isOccupied: true, passengerGender: "male" },
    { row: 1, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 2, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 3, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 3, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 3, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 4, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 3, isOccupied: false, passengerGender: "null" },
  ],
  5: [
    { row: 0, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 0, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 0, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 0, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 1, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 2, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 3, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 3, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 3, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 4, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 3, isOccupied: false, passengerGender: "null" },
  ],
  6: [
    { row: 0, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 0, col: 1, isOccupied: true, passengerGender: "male" },
    { row: 0, col: 2, isOccupied: true, passengerGender: "male" },
    { row: 0, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 1, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 2, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 3, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 3, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 4, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 3, isOccupied: true, passengerGender: "male" },
  ],
  7: [
    { row: 0, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 0, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 0, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 0, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 1, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 2, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 3, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 3, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 3, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 4, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 3, isOccupied: true, passengerGender: "male" },
  ],
  8: [
    { row: 0, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 0, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 0, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 0, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 0, isOccupied: true, passengerGender: "female" },
    { row: 1, col: 1, isOccupied: false, passengerGender: "null" },
    { row: 1, col: 2, isOccupied: true, passengerGender: "male" },
    { row: 1, col: 3, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 0, isOccupied: true, passengerGender: "male" },
    { row: 2, col: 1, isOccupied: true, passengerGender: "male" },
    { row: 2, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 2, col: 3, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 3, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 2, isOccupied: true, passengerGender: "female" },
    { row: 3, col: 3, isOccupied: true, passengerGender: "male" },
    { row: 4, col: 0, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 1, isOccupied: true, passengerGender: "female" },
    { row: 4, col: 2, isOccupied: false, passengerGender: "null" },
    { row: 4, col: 3, isOccupied: false, passengerGender: "null" },
  ],
};
