export const allTravelData = [
  {
    id: 1,
    departCity: "İstanbul",
    arrivalCity: "İzmir",
    date: "2023-08-31",
    availableSeats: 14,
    price: 100,
  },
  {
    id: 2,
    departCity: "Ankara",
    arrivalCity: "Antalya",
    date: "2023-08-31",
    availableSeats: 16,
    price: 150,
  },
  {
    id: 3,
    departCity: "İstanbul",
    arrivalCity: "Antalya",
    date: "2023-08-31",
    availableSeats: 7,
    price: 120,
  },
  {
    id: 4,
    departCity: "Ankara",
    arrivalCity: "İzmir",
    date: "2023-08-31",
    availableSeats: 13,
    price: 110,
  },
  {
    id: 5,
    departCity: "İstanbul",
    arrivalCity: "İzmir",
    date: "2023-09-01",
    availableSeats: 14,
    price: 100,
  },
  {
    id: 6,
    departCity: "Ankara",
    arrivalCity: "Antalya",
    date: "2023-09-01",
    availableSeats: 16,
    price: 150,
  },
  {
    id: 7,
    departCity: "İstanbul",
    arrivalCity: "Antalya",
    date: "2023-09-01",
    availableSeats: 7,
    price: 120,
  },
  {
    id: 8,
    departCity: "Ankara",
    arrivalCity: "İzmir",
    date: "2023-09-01",
    availableSeats: 13,
    price: 110,
  },
];
